# Generated by Django 4.0.2 on 2022-10-11 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripción')),
                ('requerida', models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=1)),
                ('tipo_dato', models.CharField(choices=[('1', 'Texto'), ('2', 'Númerico'), ('3', 'Decimal'), ('4', 'Fecha'), ('5', 'Fecha y hora'), ('6', 'Correo electrónico'), ('7', 'Selección (Combo)'), ('8', 'Selección (Opciones)')], max_length=2, verbose_name='Tipo de respuesta')),
                ('size_texto', models.SmallIntegerField(blank=True, choices=[(25, '25'), (50, '50'), (100, '100'), (150, '150'), (200, '200'), (300, '300'), (500, '500'), (700, '700'), (1000, 'Mucho texto')], null=True, verbose_name='Máximo de palabras apróximadamente')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContestaFormularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleContestaFormularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=1500)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Formulario.campo', verbose_name='Campo')),
                ('contesta_formularios', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Formulario.contestaformularios', verbose_name='Contesta')),
            ],
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionesCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=150, verbose_name='Opción')),
                ('valor', models.CharField(max_length=2)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_campo', to='Formulario.campo', verbose_name='Opciones')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.categoria', verbose_name='Sub-categoría')),
            ],
        ),
        migrations.RemoveField(
            model_name='formulario_dinamico',
            name='formulario0',
        ),
        migrations.DeleteModel(
            name='Formulaio0',
        ),
        migrations.DeleteModel(
            name='Formulario_dinamico',
        ),
        migrations.AddField(
            model_name='formularios',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.subcategoria', verbose_name='Formularios'),
        ),
        migrations.AddField(
            model_name='contestaformularios',
            name='formularios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Formulario.formularios', verbose_name='Formularios'),
        ),
        migrations.AddField(
            model_name='contestaformularios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='campo',
            name='formularios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='Formulario.formularios', verbose_name='Campo'),
        ),
    ]
