# Generated by Django 4.0.2 on 2022-10-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_campo_categoria_contestaformularios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularios',
            name='subcategoria',
        ),
        migrations.DeleteModel(
            name='SubCategoria',
        ),
    ]
