# Generated by Django 4.0.2 on 2022-11-01 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Formulario', '0003_remove_formularios_subcategoria_delete_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='campo',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='size_texto',
            field=models.SmallIntegerField(blank=True, choices=[(25, '25'), (50, '50'), (100, '100'), (150, '150'), (200, '200'), (300, '300'), (500, '500')], null=True, verbose_name='Máximo de palabras apróximadamente'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo_dato',
            field=models.CharField(choices=[('1', 'Texto'), ('2', 'Númerico'), ('3', 'Decimal'), ('4', 'Fecha'), ('5', 'Fecha y hora'), ('6', 'Correo electrónico'), ('7', 'Selección (Combo)'), ('8', 'Selección (Opciones)'), ('9', 'Archivo PDF')], max_length=2, verbose_name='Tipo de respuesta'),
        ),
        migrations.AlterField(
            model_name='contestaformularios',
            name='formularios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.formularios', verbose_name='Formularios'),
        ),
        migrations.AlterField(
            model_name='contestaformularios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='detallecontestaformularios',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.campo', verbose_name='Campo'),
        ),
        migrations.AlterField(
            model_name='detallecontestaformularios',
            name='contesta_formularios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formulario.contestaformularios', verbose_name='Contesta'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='formularios',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
