# Generated by Django 4.0.2 on 2022-06-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('decripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('apoyo', models.CharField(choices=[('1', 'Apoyo1'), ('2', 'Apoyo2'), ('3', 'Apoyo3')], max_length=1, verbose_name='Apoyo')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='convocatoria.presupuesto', verbose_name='Presupuesto')),
            ],
        ),
    ]
