# Generated by Django 4.0.2 on 2022-09-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_cierre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='hora_cierre',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
