# Generated by Django 4.0.2 on 2022-08-11 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='ninterno',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero Interno*'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoP',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='telCelular_invalido', message='Numero de telefono invalido', regex='^(\\d{10})$')], verbose_name='Teléfono Particular*'),
        ),
    ]
