# Generated by Django 4.0.2 on 2022-08-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_datospersonales_ninterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datospersonales',
            old_name='userD',
            new_name='user',
        ),
    ]
