# Generated by Django 4.0.2 on 2022-08-22 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_userd_datospersonales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cpostal',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='codigoPostal_invalido', message='El Codigo postal no tiene un formato válido', regex='^(\\d{5})$')], verbose_name='Codigo Postal'),
        ),
    ]
