# Generated by Django 4.0.2 on 2022-08-23 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_datospersonales_cpostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='telCelular_invalido', message='Numero de telefono invalido', regex='^(\\d{10})$')], verbose_name='Teléfono Celular'),
        ),
    ]
