# Generated by Django 4.0.2 on 2022-09-19 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_datospersonales_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
