# Generated by Django 4.0.2 on 2022-10-12 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_datospersonales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='estado',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.estado', verbose_name='Estado'),
        ),
    ]
